### ISSUE TITLE
Crash with PMMO when breaking any trees

### ISSUE THREAD

**Issue by Groupix05** [InvictusSlayer/DynamicTrees-Slayers-Beasts#1]
Mods version:
- Minecraft 1.20.1
- Forge 47.1.3
- TerraBlender 3.0.1.7
- Cloth Config API 11.1.118
- Project MMO 1.3.22
- Architectury API 9.2.14
- Dynamic Trees 1.3.0 BETA6
- Dynamic Trees + 1.2.0 BETA1
- Dynamic Trees Slayer's Beasts 0.1.0
- Slayer's Beasts 1.3.0

Crash report : https://mclo.gs/r8OQirz
Latest.log : https://mclo.gs/SdDtzki
debug.log : https://mclo.gs/RiBjgQb

**Comment by InvictusSlayer** [comment]
Update forge to 47.2.0 or higher.

**Comment by Groupix05** [comment]
crash with 47.3.1 :
crash log : https://mclo.gs/UpAN0WF
latest.log : https://mclo.gs/mo04fQj
debug.log : https://mclo.gs/mmYcG5I

**Comment by InvictusSlayer** [comment]
Okay just use 47.2.0 specifically then. I tested 47.1.3 which crashed and 47.2.0 did not

**Comment by Groupix05** [comment]
Is there a way to fix it for newer versions of Forge if it's on your side? And if not should I report the issue to Dynamic Trees or PMMO ?

**Comment by Groupix05** [comment]
Ok I think I found a way to fix it. I m having the same problem with DT Nature's spirit.
Will make a pull request for Dynamic Trees

**Comment by InvictusSlayer** [comment]
Nicely done! I was just investigating different versions and there seems to be a weird inconsistency with modrinth and curseforge, idk what it was about. If your fix works it shouldn't be relevant anyways.

**Comment by Groupix05** [comment]
I just did a temporary fix until PMMO fix this issue
